/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements org.apache.thrift.TEnum {
  ReferenceSignatureShortage(0),
  ReferenceSignatureQuality(1),
  AccountNotExist(2),
  TestSignatureNotFound(3),
  TooMuchTestSignatureGiven(4);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return ReferenceSignatureShortage;
      case 1:
        return ReferenceSignatureQuality;
      case 2:
        return AccountNotExist;
      case 3:
        return TestSignatureNotFound;
      case 4:
        return TooMuchTestSignatureGiven;
      default:
        return null;
    }
  }
}
