/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef opensv_CONSTANTS_H
#define opensv_CONSTANTS_H

#include "opensv_types.h"

namespace opensv {

class opensvConstants {
 public:
  opensvConstants();

};

extern const opensvConstants g_opensv_constants;

} // namespace

#endif
