/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "opensv_constants.h"

namespace opensv {

const opensvConstants g_opensv_constants;

opensvConstants::opensvConstants() {
}

} // namespace

